#!/bin/bash

# Creating Shell script for creating new user account with password and information .


# Enforcing to use ROOT user for executing this script 

if [[ $UID -eq 0 ]];
then
	echo " Script is executing with ROOT user"
else 
	echo " Please execute this Script with ROOT user ."
	exit 1
fi

# Accepting Information about account from user

read -p "Please enter USERNAME : " USERNAME

read -p "Please enter name of owner of this account : " COMMENT

# Creating passsowrd for usr which is move secure and generated by script

PASSWORD=$(date +%s%N | sha256sum | head -c36)

# printing All Information 

echo "Hi $COMMENT,
below are the details that you shared :
1) USER = $USERNAME
2) OWNER = $COMMENT
3)PASSWORD = $PASSWORD"

echo "Creating Account : "

# Creating account 

useradd -c $COMMENT -m $USERNAME

if [[ $? -eq 0 ]];
then
	echo "Account created Successfully "
else 
	echo "due to some error Account creation is failed"
	exit 1
fi

echo -e  "$PASSWORD\n$PASSWORD" | passwd "$USERNAME"

# forcing user to change password once they login for first time 

 passwd -e  $USERNAME

# Below we are displaying username , password and hostname

HOST=$(whoami)
echo " 
1) USER : $USERNAME
2) PASSWORD : $PASSWORD
3) HOSTNAME : $HOST
"
# displaying the last three accont created

echo "below are latest 3 account created :"
tail -3 /etc/passwd |  cut -d: -f1

exit 0
